source 'https://rubygems.org'

gem 'rails', '4.1.9'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'slim-rails'
gem 'board', path: '../board'
gem 'authenticated_board', path: '../authenticated_board'
gem 'persistence', path: '../persistence'
gem 'markdown_standup_email_formatter', path: '../markdown_standup_email_formatter'
gem 'email_client', path: '../email_client'
gem 'wordpress_client', path: '../wordpress_client'
gem 'sqlite3'

gem 'jquery-rails'
gem 'turbolinks'
gem 'omniauth-google-oauth2'

group :development do
  gem 'letter_opener'
end

group :test do
  gem 'rspec-rails'
end
