source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'slim-rails'
gem 'board', path: '../board'

gem 'jquery-rails'
gem 'turbolinks'
