source 'https://rubygems.org'

gem 'rails', '4.1.9'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'slim-rails'
gem 'board', path: '../board'
gem 'persistence', path: '../persistence'
gem 'sqlite3'

gem 'jquery-rails'
gem 'turbolinks'

group :development, :test do
  gem 'capybara'
  gem 'cucumber'
end